// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pouylevngsyeecuyevaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvdXlsZXZuZ3N5ZWVjdXlldmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTY3OTgsImV4cCI6MjA3MDUzMjc5OH0.Y3dHZ7aJteIq2Swk_1IjLiPvRVcPIMOf040gziFz_0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});